### ISSUE TITLE
Issue with IState

### ISSUE THREAD

**Issue by bad-drawer** [marcel-k/UiRouterStickyStates#1]
In the ui-router-extras.d.ts file, I'm getting "Interface 'ng.ui.extras.IState' incorrectly extends interface ng.ui.IState'". Is this supposed to extend a different interface?

**Comment by marcel-k** [comment]
Hi, 

Yes it depends on the angular-ui-router definition file: 

``` javascript
/// <reference path="../angular-ui-router/angular-ui-router.d.ts" />
```

Its possible its out of date though.. 

btw I recommend using the definition file in the DefinityTyped repo <a href="https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/ui-router-extras/ui-router-extras.d.ts">here</a>.
Mabe you could do a pull request if it is in fact out of sync with the current version of the d.ts file of angular-ui-router.
